language: c

before_install:
  - sudo apt-get -y install build-essential libluajit-5.1-dev

script:
  - git submodule add https://github.com/Theintercooler/libuv.git libraries/uv
  - (mkdir cmakebuild && cd cmakebuild && cmake -DHAVE_LOCAL_LIBUV=1 .. && make -j5 && cd .. && rm -rf cmakebuild)

compiler:
  - clang
  - gcc
  
notifications:
  webhooks: http://n.tkte.ch/h/1190/FtqFf9yfzU4_ZtwbgF3-rHUh
